-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 05:49:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca` ;

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`alumno` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`alumno` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(13) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `correo_electronico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_alumno`),
  UNIQUE INDEX `rut` (`rut` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`bibliotecario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`bibliotecario` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`bibliotecario` (
  `id_bibliotecario` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(13) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `correo_electronico` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `rol` ENUM('jefe_bibliotecario', 'bibliotecario') NULL DEFAULT 'bibliotecario',
  PRIMARY KEY (`id_bibliotecario`),
  UNIQUE INDEX `rut` (`rut` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`auditoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`auditoria` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`auditoria` (
  `id_auditoria` INT NOT NULL AUTO_INCREMENT,
  `id_bibliotecario` INT NOT NULL,
  `tabla_afectada` VARCHAR(100) NOT NULL,
  `id_registro_afectado` INT NOT NULL,
  `detalle_cambio` TEXT NULL DEFAULT NULL,
  `tipo_accion` ENUM('inserccion', 'actualizacion', 'eliminacion') NOT NULL,
  PRIMARY KEY (`id_auditoria`),
  INDEX `fk_auditoria_bibliotecario` (`id_bibliotecario` ASC) VISIBLE,
  CONSTRAINT `fk_auditoria_bibliotecario`
    FOREIGN KEY (`id_bibliotecario`)
    REFERENCES `biblioteca`.`bibliotecario` (`id_bibliotecario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`libros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`libros` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`libros` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `editorial` VARCHAR(100) NOT NULL,
  `ano_publicacion` YEAR NOT NULL,
  `ISBN` VARCHAR(100) NOT NULL,
  `genero` VARCHAR(100) NOT NULL,
  `idioma` VARCHAR(100) NOT NULL,
  `ubicacion` VARCHAR(100) NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  `cantidad_prestada` INT NOT NULL,
  PRIMARY KEY (`id_libro`),
  UNIQUE INDEX `ISBN` (`ISBN` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`prestamo` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`prestamo` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `id_alumno` INT NOT NULL,
  `id_libro` INT NOT NULL,
  `id_bibliotecario` INT NOT NULL,
  `fecha_prestamo` DATE NOT NULL,
  `fecha_devolucion` DATE NULL DEFAULT NULL,
  `fecha_limite_devolucion` DATE NOT NULL,
  `estado_devolucion` ENUM('pendiente', 'devuelta', 'con retraso') NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  INDEX `fk_prestamo_alumno` (`id_alumno` ASC) VISIBLE,
  INDEX `fk_prestamo_libro` (`id_libro` ASC) VISIBLE,
  INDEX `fk_prestamo_bibliotecario` (`id_bibliotecario` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_alumno`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `biblioteca`.`alumno` (`id_alumno`),
  CONSTRAINT `fk_prestamo_bibliotecario`
    FOREIGN KEY (`id_bibliotecario`)
    REFERENCES `biblioteca`.`bibliotecario` (`id_bibliotecario`),
  CONSTRAINT `fk_prestamo_libro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `biblioteca`.`libros` (`id_libro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`salaEstudio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`salaEstudio` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`salaEstudio` (
  `id_sala` INT NOT NULL AUTO_INCREMENT,
  `nombre_sala` VARCHAR(200) NOT NULL,
  `capacidad` INT NOT NULL,
  `equipamiento` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`reserva` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `id_alumno` INT NOT NULL,
  `id_sala` INT NOT NULL,
  `id_bibliotecario` INT NOT NULL,
  `hora_inicio` DATETIME NOT NULL,
  `hora_fin` DATETIME NOT NULL,
  `estado_reserva` ENUM('pendiente', 'confirmada', 'cancelada') NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_alumno` (`id_alumno` ASC) VISIBLE,
  INDEX `fk_reserva_sala` (`id_sala` ASC) VISIBLE,
  INDEX `fk_reserva_bibliotecario` (`id_bibliotecario` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_alumno`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `biblioteca`.`alumno` (`id_alumno`),
  CONSTRAINT `fk_reserva_bibliotecario`
    FOREIGN KEY (`id_bibliotecario`)
    REFERENCES `biblioteca`.`bibliotecario` (`id_bibliotecario`),
  CONSTRAINT `fk_reserva_sala`
    FOREIGN KEY (`id_sala`)
    REFERENCES `biblioteca`.`salaEstudio` (`id_sala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
-------------------------------------------------------
-- INSERTAR `LIBROS`
-------------------------------------------------------
INSERT INTO libros (titulo, autor, editorial, ano_publicacion, isbn, genero, idioma, ubicacion, cantidad_disponible, cantidad_prestada)
VALUES
    ('El código Da Vinci', 'Dan Brown', 'Planeta', 2003, '9788408011729', 'Misterio', 'Español', 'Sector A', 5, 0),
    ('1984', 'George Orwell', 'Debolsillo', 2017, '9788466339532', 'Ciencia ficción', 'Español', 'Sector B', 3, 0),
    ('Cien años de soledad', 'Gabriel García Márquez', 'Diana', 1967, '9788497592208', 'Realismo mágico', 'Español', 'Sector C', 7, 0),
    ('Harry Potter y la piedra filosofal', 'J.K. Rowling', 'Salamandra', 1999, '9788478884450', 'Fantasía', 'Español', 'Sector D', 4, 0),
    ('The Catcher in the Rye', 'J.D. Salinger', 'Back Bay Books', 2001, '9780316769488', 'Novela', 'Inglés', 'Sector E', 6, 0),
    ('To Kill a Mockingbird', 'Harper Lee', 'Harper Perennial Modern Classics', 2006, '9780061120084', 'Ficción', 'Inglés', 'Sector F', 2, 0),
    ('Pride and Prejudice', 'Jane Austen', 'Penguin Classics', 2003, '9780141439518', 'Romance', 'Inglés', 'Sector G', 8, 0),
    ('Don Quijote de la Mancha', 'Miguel de Cervantes', 'Espasa-Calpe', 2004, '9788421693730', 'Novela', 'Español', 'Sector H', 5, 0),
    ('The Lord of the Rings', 'J.R.R. Tolkien', 'Houghton Mifflin Harcourt', 2004, '9780618640157', 'Fantasía', 'Inglés', 'Sector I', 3, 0),
    ('The Great Gatsby', 'F. Scott Fitzgerald', 'Scribner', 2004, '9780743273565', 'Ficción', 'Inglés', 'Sector J', 4, 0);
-------------------------------------------------------
-- INSERTAR `salaEstudio`
-------------------------------------------------------
INSERT INTO salaEstudio (nombre_sala, capacidad, equipamiento)
VALUES
    ('Sala 1', 10, 'Mesas y sillas'),
    ('Sala 2', 8, 'Pizarra y proyector'),
    ('Sala 3', 12, 'Computadoras'),
    ('Sala 4', 6, 'Sillones y biblioteca');
-------------------------------------------------------
-- INSERTAR `alumno`
-------------------------------------------------------
INSERT INTO alumno (rut, nombre, correo_electronico)
VALUES
    ('12345678-9', 'Juan Pérez', 'juanperez@example.com'),
    ('98765432-1', 'María Gómez', 'mariagomez@example.com'),
    ('45678901-2', 'Carlos Rodríguez', 'carlosrodriguez@example.com');
-------------------------------------------------------
-- INSERTAR `bibliotecario`
-------------------------------------------------------
INSERT INTO bibliotecario (rut, nombre, correo_electronico, contrasena, rol)
VALUES
    ('23456789-0', 'Ana Martínez', 'anamartinez@example.com', 'clave123', 'bibliotecario'),
    ('34567890-1', 'Luis García', 'luisgarcia@example.com', 'contraseña456', 'jefe_bibliotecario');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
